### PR TITLE
Fixes League Of Legends markers

### LINKED ISSUE #202: League of Legends Markers Broken
Seems like with patch 14.10, the markers don't work anymore, this was the thing telling you what champ you played, W/L, scoreline, and then the bookmarks on kill, assist, or death.

YCaXYzI

### PR DESCRIPTION
**Pull request by Segergren**
Fixes #202

### CODE REVIEW

**Comment by yoshinoa** [comment]
Don't mean to intrude, just a note that if you don't mind doing another external API call you can get the most recent patch at https://ddragon.leagueoflegends.com/api/versions.json

**Comment by lulzsun** [comment]
> if you don't mind doing another external API call you can get the most recent patch at https://ddragon.leagueoflegends.com/api/versions.json

@Segergren Do you think is a good idea for this pull request?

File: Classes/Integrations/LeagueOfLegendsIntegration.cs [hunk 1]
```diff
@@ -53,7 +53,7 @@ internal class LeagueOfLegendsIntegration : Integration {
                     JsonElement allPlayers = root.GetProperty("allPlayers");
                     JsonElement currentPlayer = allPlayers
                         .EnumerateArray()
-                        .FirstOrDefault(playerElement => playerElement.GetProperty("summonerName").GetString() == username.Split('#')[0]);
```
Comment (lulzsun) [inline Classes/Integrations/LeagueOfLegendsIntegration.cs:56]: I don't play League much anymore so I don't know exactly what has changed, but shouldn't we be keeping this to handle Riot ID names? Or does that not matter?

Comment (Segergren) [reply Classes/Integrations/LeagueOfLegendsIntegration.cs:56]: Yeah, I changed it to riotId. They updated it so that the summonerName now includes the # number.
But i think riotId is better to use.

**Comment by Segergren** [comment]
> Don't mean to intrude, just a note that if you don't mind doing another external API call you can get the most recent patch at [ddragon.leagueoflegends.com/api/versions.json](https://ddragon.leagueoflegends.com/api/versions.json)

I updated it to fetch the latest version once a day 🙂

**Review by lulzsun — APPROVED** [review]
Looks good, thanks!

**Comment by Segergren** [comment]
I will refactor this in a new MR
